[build]
builder = "nixpacks"

[deploy]
startCommand = "npm run start:prod"
restartPolicyType = "on_failure"

[[services]]
name = "backend"
source = "backend"

[services.build]
buildCommand = "npm run build"

[services.deploy]
startCommand = "npm run start:prod"

[services.build.variables]
NODE_VERSION = "20"

[services.deploy.variables]
PORT = "3001"
NODE_ENV = "production"
